apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcp-sre-ds-argowf-api-basic-prd
  labels:
    app: hcp-sre-ds-argowf-api-basic-prd
    prjId: hcp-sre-ds
    rscId: hcp-sre-ds-argowf-api
    target: basic
    env: prd
    locId: hy-koic-k8s-app-d01
spec:
  replicas: "[설정 값 변경 불가]"
  selector:
    matchLabels:
      app: hcp-sre-ds-argowf-api-basic-prd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hcp-sre-ds-argowf-api-basic-prd
        ## 필수
        prjId: hcp-sre-ds
        rscId: hcp-sre-ds-argowf-api
        target: basic
        env: prd
        locId: hy-koic-k8s-app-d01
        ## 추가
        prjCat: Platform
        svcType: app
        appType: WP-PYTHON
        logging: project
    spec:
      containers:
      - name: hcp-sre-ds-argowf-api-basic-prd
        image: "[설정 값 변경 불가]"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: spring.profiles.active
          value: prd
        - name: user.timezone
          value: Asia/Seoul
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 30
        livenessProbe:
          httpGet:
            path: /hcp-sre-ds-argowf-api/swagger.json
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /hcp-sre-ds-argowf-api/swagger.json
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
          failureThreshold: 10
        resources:
          limits:
            cpu: "[설정 값 변경 불가]"
            memory: "[설정 값 변경 불가]"
          requests:
            cpu: "[설정 값 변경 불가]"
            memory: "[설정 값 변경 불가]"
        volumeMounts:
        - name: timezone-config
          mountPath: /etc/localtime
      volumes:
      - name: timezone-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      serviceAccountName: default
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: hcp-sre-ds-argowf-api-basic-prd-svc
  labels:
    app: hcp-sre-ds-argowf-api-basic-prd
    prjId: hcp-sre-ds
    rscId: hcp-sre-ds-argowf-api
    target: basic
    env: prd
    locId: hy-koic-k8s-app-d01
spec:
  selector:
    app: hcp-sre-ds-argowf-api-basic-prd
  ports:
  - name: tcp
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hcp-sre-ds-argowf-api-basic-prd-ingress
  labels:
    app: hcp-sre-ds-argowf-api-basic-prd
    prjId: hcp-sre-ds
    rscId: hcp-sre-ds-argowf-api
    target: basic
    env: prd
    locId: hy-koic-k8s-app-d01
#  annotations:
#    ingress.kubernetes.io/rewrite-target: /hcp-sre-ds-argowf-api/
spec:
  rules:
  - host: hcp-sre-ds-argowf-api-basic-prd.api.hcpnd01.skhynix.com
    http:
      paths:
#      - path: /hcp-sre-ds-argowf-api/
      - path: /
        backend:
          serviceName: hcp-sre-ds-argowf-api-basic-prd-svc
          servicePort: 5000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hcp-sre-ds-argowf-api-basic-prd-hpa
  labels:
    app: hcp-sre-ds-argowf-api-basic-prd
    prjId: hcp-sre-ds
    rscId: hcp-sre-ds-argowf-api
    target: basic
    env: prd
    locId: hy-koic-k8s-app-d01
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hcp-sre-ds-argowf-api-basic-prd
  minReplicas: "[설정 값 변경 불가]"
  maxReplicas: "[설정 값 변경 불가]"
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70